template = "https://github.com/giellalt/template-lang-und"
rev_id = 328
template_sha = "a66ce6606ea33e46cd3439c88cafa44d4dcdde92"

[replacements]
__GLOTTOLOG_ID__ = "kild1236"
__REPO__ = "lang-sjd"
__UND2C__ = "sjd"
__UNDEFINED__ = "Kildin Sami"
__UND__ = "sjd"
