template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "kild1236"
__REPO__ = "lang-sjd"
__UND2C__ = "sjd"
__UNDEFINED__ = "Kildin Sami"
__UND__ = "sjd"
