[package]
name = "sjd"
human_name = "Kildin Sami"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.sjd]
filename = "sjd-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-sjd"
platform = "windows"
uuid = "8438EAA8-D729-4B11-A794-8CAC68346802"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.sjd"
package = "speller-sjd"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-sjd-mso"
platform = "windows"
uuid = "B620EA1F-7E32-48E0-99FF-350041A2E989"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-sjd"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
